security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oauth:
            id: goldenline.oauth.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            oauth:
                resource_owners:
                    goldenline: /logowanie/goldenline
                    facebook:   /logowanie/facebook
                login_path:     /logowanie
                failure_path:   /logowanie
                oauth_user_provider:
                    service: goldenline.oauth.user_provider
            logout:
                path:   /wylogowanie
                target: /

    access_control:
        - { path: ^/logowanie, roles: IS_AUTHENTICATED_ANONYMOUSLY}
